version: '2.2'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - DATABASE_USERNAME=sa
      - SA_PASSWORD=YourStrong!Password
    ports:
      - '1433:1433'
    networks:
      - my-network

    # ms-account:
    #   build:
    #     context: .
    #     dockerfile: Dockerfile-msaccount
    #   container_name: ms-account
    #   restart: always
    #   environment:
    #     - PORT=5001
    #   ports:
    #     - '5001:5001'
    #   volumes:
    #     - ./:/usr/src/app/
    #   networks:
    #     - my-network

  ms-task:
    build:
      context: .
      dockerfile: Dockerfile-mstask
    container_name: ms-task
    environment:
      - PORT=5007
    ports:
      - '5007:5007'
    volumes:
      - ./:/usr/src/app/
    networks:
      - my-network

  ms-project:
    build:
      context: .
      dockerfile: Dockerfile-msproject
    container_name: ms-project
    restart: always
    environment:
      - PORT=5005
    ports:
      - '5005:5005'
    volumes:
      - ./:/usr/src/app/
    networks:
      - my-network

  # ms-document:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-msdocument
  #   container_name: ms-document
  #   restart: always
  #   environment:
  #     - PORT=5003
  #   ports:
  #     - '5003:5003'
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - '5003:5003'
  #   networks:
  #     - my-network

networks:
  my-network:
