version: v0.4.6-alpha.1

dsn: memory

serve:
  public:
    base_url: http://192.168.29.131:4455/.ory/kratos/public/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://192.168.29.131:4455/
  whitelisted_return_urls:
    - http://192.168.29.131:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://192.168.29.131:4455/error

    settings:
      ui_url: http://192.168.29.131:4455/home/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://192.168.29.131:4455/recovery

    verification:
      enabled: true
      ui_url: http://192.168.29.131:4455/verify
      after:
        default_browser_return_url: http://192.168.29.131:4455/

    logout:
      after:
        default_browser_return_url: http://192.168.29.131:4455/auth/login

    login:
      ui_url: http://192.168.29.131:4455/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://192.168.29.131:4455/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    # connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    connection_uri: smtp://test@softobiz.com:Xum83875@smtp.office365.com:587/?skip_ssl_verify=false
    from_address: test@softobiz.com
